Add data schemes for server
StanfordBDHG/ENGAGE-HF-Firebase pull request #13
Opened 2024-06-26 22:58 UTC by pauljohanneskraft

# *Name of the PR*

## :recycle: Current situation & Problem
The data scheme document is still missing some parts especially relevant to the server, especially organization handling, clinicians and kccq scores.

## :gear: Release Notes 
Added new sections to data scheme document for the server.

## :books: Documentation
- 

## :white_check_mark: Testing
-

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

2024-06-26 22:59 UTC, pauljohanneskraft commented
Opened as a draft since I am not yet sure whether all the missing parts for the server are covered already in this PR.

2024-06-28 20:22 UTC, PSchmiedmayer requested changes
Thank you for working on this @pauljohanneskraft!

These changes look great and fill in a good amount of missing pieces.
In addition, we are currently missing is roles and permissions for a clinician as well as results from the algorithm as recommendations for patients and something to surface in the dashboard for clinicians.

We would need to attach a role to a clinician and we need to define the types of roles and what they should access. We should explore this in combination with having cloud functions that observe clinician roles and changes in roles -> permissions mappings and store these as claims in Firebase Auth (https://firebase.google.com/docs/auth/admin/custom-claims).

WIll also add this to #7.

2024-06-28 20:23 UTC, pauljohanneskraft commented on README.md
> +|leader|string|e.g. "Alex Sandhu, MD"|-|
What about `contactName`? With `contact` I would usually think of a reference to a user/clinician

2024-06-28 20:24 UTC, pauljohanneskraft commented on README.md
> +TBD: How is the connection between clinician and patient established? Does the patient select the clinician or vice-versa, or does the organization assign them? Clinicians can assign clinicians to pa
makes sense, will do

2024-06-28 20:24 UTC, pauljohanneskraft commented on README.md
> +### /users/$userId$/kccqResults/$kccqResultId$
it will probably be renamed to kccqScores, hope thats fine

2024-06-28 20:24 UTC, PSchmiedmayer commented on README.md
> +|leader|string|e.g. "Alex Sandhu, MD"|-|
Sounds great to me!

2024-06-28 20:24 UTC, PSchmiedmayer commented on README.md
> +### /users/$userId$/kccqResults/$kccqResultId$
Sounds good to me!

2024-07-16 00:11 UTC, PSchmiedmayer commented
Feel free to tag me here & on Slack in case you need a re-review of the PR 🚀

2024-07-19 17:00 UTC, closed without merging